version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - webapp
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../:/webapp:rw
    networks:
      default:
        aliases:
          - localhost

  webapp:
    build:
      context: ./docker/webapp
      dockerfile: Dockerfile
    command: >
       bash -c "touch log/nginx.access.log && touch log/nginx.error.log &&
                yarn install &&
                yarn setup &&
                yarn start"
    volumes:
      - ../:/webapp
      - /webapp/node_modules
      - /build
    ports:
      - "3000:3000"

